### PR TITLE
Signed-off-by: Catherine Liu <catherine.liu@cloud.com>

### PR DESCRIPTION
**Pull request by catherineliuchina**
CP-43371: Release Generated HTML based Certs Guides to HCL Website through pipeline
Move doc from ACK doc repo to ACK code repo
	new file:   docs/ack_img/ack03.png
	new file:   docs/ack_img/ack04.png
	new file:   docs/ack_img/ack05.png
	new file:   docs/ack_img/ack06.png
	new file:   docs/ack_img/ack07.png
	new file:   docs/ack_img/ack08.png
	new file:   docs/ack_img/ack09.png
	new file:   docs/ack_img/ack10.png
	new file:   docs/ack_img/ack11.png
	new file:   docs/ack_img/ack12.png
	new file:   docs/ack_img/ack13.png
	new file:   docs/ack_img/ack14.png
	new file:   docs/ack_img/ack15.png
	new file:   docs/ack_img/ack16.png
	new file:   docs/ack_img/ack17.png
	new file:   docs/ack_img/ack18.png
	new file:   docs/ack_img/ack19.jpg
	new file:   docs/ack_img/ack20.jpg
	new file:   docs/ack_img/ack21.jpg
	new file:   docs/ack_img/ack22.jpg
	new file:   docs/ack_img/ack23.jpg
	new file:   docs/ack_img/ack24.jpg
	new file:   docs/xenserver-automated-certification-kit-guide.md
	new file:   docs/xenserver-sr-iov-certification-form.docx

### CODE REVIEW

**Review by DeliZhangX — APPROVED** [review]

**Comment by lindig** [comment]
What is this? Please add some context in a commit message.

**Comment by catherineliuchina** [comment]
> What is this? Please add some context in a commit message.

Hi Lin:

According to internal discussion, we decided to move certs kits document from doc repo to code. In this way. we can easily to associate certs kits document with relevant code. Thanks

**Comment by Zhengchai** [comment]
Please add a message/note to your PR title, thanks

**Comment by lindig** [comment]
This is sitting here for two weeks without any reviews. Please get this reviewed or close it. @catherineliuchina @Zhengchai

**Review by stephenchengCloud — APPROVED** [review]

**Pull request merged**
