### PR TITLE
Signed-off-by: Catherine Liu <catherine.liu@cloud.com>

### PR DESCRIPTION
**Pull request by catherineliuchina**
CA-377157 update copyright from "Cloud Software Group Holdings, Inc." to "Cloud Software Group, Inc."
 Changes to be committed:
	modified:   docs/xenserver-automated-certification-kit-guide.md

### CODE REVIEW

**Comment by edwintorok** [comment]
The signed-off-by is in the wrong place, it should go onto the last line of the commit message, instead of the first line (the first line is used as the title).

If you use 'git commit --amend -s' it'll add the signoff in the appropriate place.

**Comment by lindig** [comment]
The commit still has the sign-off in the subject line; it should be a summary.

**Comment by DeliZhangX** [comment]
You can learn from other commits if not sure the summary and description style, e.g. Add ":" after ticket number...

**Review by lindig — APPROVED** [review]

**Comment by lindig** [comment]
@DeliZhangX @Zhengchai please progress this by reviewing or closing this

**Review by DeliZhangX — APPROVED** [review]

**Pull request closed without merging**
